code --install-extension abusaidm.html-snippets
code --install-extension bceskavich.theme-dracula-at-night
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dbankier.vscode-instant-markdown
code --install-extension donjayamanne.jquerysnippets
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension idleberg.icon-fonts
code --install-extension jchannon.csharpextensions
code --install-extension k--kato.docomment
code --install-extension ms-dotnettools.blazorwasm-companion
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsts.team
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mubaidr.vuejs-extension-pack
code --install-extension octref.vetur
code --install-extension pranaygp.vscode-css-peek
code --install-extension quicktype.quicktype
code --install-extension ritwickdey.LiveServer
code --install-extension RobHolme.hl7tools
code --install-extension sdras.vue-vscode-snippets
code --install-extension shardulm94.trailing-spaces
code --install-extension sporiley.css-auto-prefix
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wcwhitehead.bootstrap-3-snippets
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Zignd.html-css-class-completion
